# Generated by Django 3.0.5 on 2020-04-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='job_post_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account_id', models.IntegerField(unique=True)),
                ('job_post_id', models.IntegerField(unique=True)),
                ('apply_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='job_post_skill_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_id', models.IntegerField()),
                ('job_post_id', models.IntegerField()),
                ('skill_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='job_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='job_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('is_company_name_hidden', models.CharField(max_length=1)),
                ('create_date', models.DateTimeField()),
                ('job_description', models.TextField()),
                ('is_active', models.CharField(max_length=1)),
                ('job_title', models.CharField(max_length=50)),
                ('closing_date', models.DateField()),
                ('minimum_pay', models.FloatField()),
                ('maximum_pay', models.FloatField()),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('job_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job_location')),
                ('job_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job_type')),
                ('posted_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job_post_activity')),
            ],
        ),
    ]
