# Generated by Django 3.0.5 on 2020-04-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seeker_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('current_salary', models.IntegerField()),
                ('is_annnually_monthly', models.CharField(max_length=1)),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skill_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='seeker_skill_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField()),
                ('skill_set_id', models.ManyToManyField(to='seeker.skill_set')),
                ('user_account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_profile')),
            ],
        ),
        migrations.CreateModel(
            name='experience_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_job', models.CharField(max_length=1)),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField(unique=True)),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('job_location_city', models.CharField(max_length=50)),
                ('job_location_state', models.CharField(max_length=50)),
                ('job_location_country', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=4000)),
                ('user_account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_profile')),
            ],
        ),
        migrations.CreateModel(
            name='education_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_degree_name', models.CharField(max_length=50, unique=True)),
                ('major', models.CharField(max_length=50, unique=True)),
                ('institute_university_name', models.CharField(max_length=50)),
                ('starting_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('percentage', models.IntegerField()),
                ('CGPA', models.IntegerField()),
                ('user_account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker_profile')),
            ],
        ),
    ]
