# Generated by Django 3.0.5 on 2020-04-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='is_annnually_monthly',
            field=models.CharField(choices=[('monthly', 'monthly'), ('annually', 'annually')], max_length=10),
        ),
    ]
