# Generated by Django 3.0.5 on 2020-04-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_profile',
            name='first_name',
            field=models.CharField(default='Vishva', max_length=50),
        ),
        migrations.AlterField(
            model_name='seeker_profile',
            name='last_name',
            field=models.CharField(default='M', max_length=50),
        ),
    ]
